
import { Theme } from "theme.slint";
import { SpinnerIcon } from "icons.slint";

export component LoadingSpinner inherits Rectangle {
    width: 48px;
    height: 48px;
    SpinnerIcon {
        width: 100%;
        height: 100%;
        colorize: Theme.accent_2;

        transform-rotation: (animation-tick() / 1s) * 360deg;

        transform-origin: { x: self.width / 2, y: self.height / 2 };
    }
}

export component LoaderArea inherits Rectangle {
    in property <bool> is-loading;
    @children

    if is-loading: Rectangle {
        LoadingSpinner { }
    }
}
