[package]
name = "table"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tracing = { workspace = true }
windows-canvas = { workspace = true }
windows-collections = { workspace = true }
windows-core = { workspace = true }
windows-numerics = { workspace = true }
windows-reactor = { workspace = true }

[[bin]]
name = "table-demo"
path = "demo/main.rs"
test = false

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
