[defaults]
root = "assets/ui"
paint = { light = "#1a1a1a", dark = "#ffffff" }

[link]
includes = ["icons.vendor.gui.toml"]

[app]
iconify = "fluent-color:apps-24"
paint = "none"

[apps-list]
iconify = "fluent-color:apps-list-24"
paint = "none"

[arrow-up-filled]
iconify = "fluent:arrow-up-24-filled"

[arrow-up-regular]
file = "arrow-up-regular.svg"

[pin]
iconify = "fluent:pin-24-regular"

[pin-off]
iconify = "fluent:pin-off-24-regular"

[pin-filled]
iconify = "fluent:pin-24-filled"

[checkmark]
iconify = "fluent:checkmark-24-regular"

[chevron-up-regular]
iconify = "fluent:chevron-up-24-regular"

[chevron-down-regular]
iconify = "fluent:chevron-down-24-regular"

[chevron-right-regular]
iconify = "fluent:chevron-right-24-regular"

[color]
iconify = "fluent:color-24-regular"

[start-page]
iconify = "fluent:window-text-20-regular"

[top-speed]
iconify = "fluent:top-speed-24-regular"

[byte-units]
iconify = "fluent:ruler-24-regular"

[network-units]
iconify = "fluent:arrow-swap-24-regular"

[sidebar-charts]
iconify = "fluent:data-trending-24-regular"

[system]
file = "system.svg"
paint = "none"

[toolbox]
iconify = "fluent:toolbox-24-regular"

[open-external]
iconify = "fluent:open-24-regular"

[tool-task-manager]
iconify = "fluent:data-usage-24-regular"

[tool-resource-monitor]
iconify = "fluent:gauge-24-regular"

[tool-performance-monitor]
iconify = "fluent:data-line-24-regular"

[tool-reliability-monitor]
iconify = "fluent:heart-pulse-24-regular"

[tool-system-information]
iconify = "fluent:info-24-regular"

[tool-directx-diagnostic]
iconify = "fluent:stethoscope-24-regular"

[tool-event-viewer]
iconify = "fluent:document-bullet-list-24-regular"

[tool-services]
iconify = "fluent:puzzle-piece-24-regular"

[tool-task-scheduler]
iconify = "fluent:calendar-clock-24-regular"

[tool-device-manager]
iconify = "fluent:developer-board-24-regular"

[tool-disk-management]
iconify = "fluent:hard-drive-24-regular"

[tool-computer-management]
iconify = "fluent:desktop-24-regular"

[tool-registry-editor]
iconify = "fluent:database-24-regular"

[tool-system-properties]
iconify = "fluent:laptop-settings-24-regular"

[tool-environment-variables]
iconify = "fluent:braces-variable-24-regular"

[tool-startup-apps]
iconify = "fluent:rocket-24-regular"

[tool-installed-apps]
iconify = "fluent:apps-24-regular"

[tool-storage]
iconify = "fluent:storage-24-regular"

[tool-power]
iconify = "fluent:power-24-regular"

[tool-windows-update]
iconify = "fluent:arrow-sync-circle-24-regular"

[tool-about]
iconify = "fluent:laptop-24-regular"

[tool-process-explorer]
iconify = "fluent:apps-list-detail-24-regular"

[tool-process-monitor]
iconify = "fluent:document-search-24-regular"

[tool-autoruns]
iconify = "fluent:flash-24-regular"

[tool-tcpview]
iconify = "fluent:plug-connected-24-regular"

[tool-rammap]
iconify = "fluent:memory-16-regular"

[tool-vmmap]
iconify = "fluent:table-24-regular"

[coin]
iconify = "fluent-color:coin-multiple-24"
paint = "none"

[dashed-settings]
file = "dashed-settings.svg"
paint = "none"

[data-area]
iconify = "fluent-color:data-area-20"
paint = "none"

[database]
iconify = "fluent-color:database-24"
paint = "none"

[delete]
iconify = "fluent:delete-24-regular"

[dismiss]
iconify = "fluent:dismiss-20-regular"

[download-regular]
iconify = "fluent:arrow-download-24-regular"

[extension]
file = "extension.svg"

[eye-off]
iconify = "fluent:eye-off-24-regular"

[filter]
iconify = "fluent:filter-24-regular"

[folder]
iconify = "fluent:folder-24-regular"

[app-generic]
iconify = "fluent:app-generic-24-regular"

[tree]
iconify = "fluent:text-bullet-list-tree-24-regular"

[gears]
iconify = "carbon:gears"

[group-list]
iconify = "fluent:tab-group-24-filled"

[group-list-filled]
iconify = "fluent:tab-group-24-filled"

[group-list-regular]
iconify = "fluent:tab-group-24-regular"

[image-search]
iconify = "fluent:image-search-20-regular"

[info]
file = "info.svg"

[layer-filled]
file = "layer-filled.svg"
paint = "none"

[layer-regular]
iconify = "fluent:layer-24-regular"

[maximize]
iconify = "fluent:maximize-16-regular"

[minimize]
iconify = "fluent:subtract-24-regular"

[new-task]
file = "new-task.svg"

[open]
iconify = "fluent:open-20-regular"

[pause]
iconify = "fluent:pause-24-regular"

[people]
iconify = "fluent-color:people-24"
paint = "none"

[play]
iconify = "fluent:play-24-regular"

[plus]
iconify = "fluent:add-32-light"

[proc-filled]
file = "proc-filled.svg"

[proc-regular]
file = "proc-regular.svg"

[prohibited]
iconify = "fluent:prohibited-24-regular"

[pulse-filled]
file = "pulse-filled.svg"

[pulse-regular]
file = "pulse-regular.svg"

[puzzle]
iconify = "fluent-color:puzzle-piece-24"
paint = "none"

[refresh]
iconify = "fluent:arrow-sync-24-regular"

[restore]
file = "restore.svg"

[search]
iconify = "fluent:search-24-regular"

[more-horizontal]
iconify = "fluent:more-horizontal-24-regular"

[settings]
iconify = "fluent-color:settings-24"
paint = "none"

[settings-filled]
iconify = "fluent:settings-24-filled"

[settings-regular]
iconify = "fluent:settings-24-regular"

[spinner]
iconify = "fluent:spinner-ios-20-regular"

[statistics]
iconify = "fluent-color:data-trending-24"
paint = "none"

[stop]
iconify = "fluent:stop-24-regular"

[terminate]
iconify = "fluent:dismiss-circle-24-regular"

[window]
iconify = "fluent:window-24-regular"

[activity]
iconify = "fluent-color:history-24"
paint = "none"

[came]
iconify = "fluent:arrow-up-right-24-regular"
paint = { light = "#0F7B0F", dark = "#6CCB5F" }

[went]
iconify = "fluent:arrow-down-left-24-regular"
paint = { light = "#C42B1C", dark = "#FF99A4" }

[burst]
iconify = "fluent:stack-24-regular"

[uniproc-logo]
file = "uniproc-logo.svg"
paint = "none"

[uniproc-logo-splash]
file = "uniproc-logo-splash.svg"
paint = "none"

[sys.application.icon]
file = "app.svg"
windows-ico = "icon.ico"
paint = "none"
