[defaults]
root = "crates/slint-adapter/ui/assets"

[link]
includes = ["icons.vendor.gui.toml"]

[app]
iconify = "fluent-color:apps-24"

[apps-list]
iconify = "fluent-color:apps-list-24"

[arrow-up-filled]
iconify = "fluent:arrow-up-24-filled"

[arrow-up-regular]
file = "arrow-up-regular.svg"

[coin]
iconify = "fluent-color:coin-multiple-24"

[dashed-settings]
file = "dashed-settings.svg"

[data-area]
iconify = "fluent-color:data-area-20"

[database]
iconify = "fluent-color:database-24"

[dismiss]
iconify = "fluent:dismiss-20-regular"

[download-regular]
iconify = "fluent:arrow-download-24-regular"

[extension]
file = "extension.svg"

[folder]
iconify = "fluent:folder-24-regular"

[gears]
iconify = "carbon:gears"

[group-list]
iconify = "fluent:tab-group-24-filled"

[group-list-filled]
iconify = "fluent:tab-group-24-filled"

[group-list-regular]
iconify = "fluent:tab-group-24-regular"

[image-search]
iconify = "fluent:image-search-20-regular"

[info]
file = "info.svg"

[layer-filled]
file = "layer-filled.svg"

[layer-regular]
iconify = "fluent:layer-24-regular"

[maximize]
iconify = "fluent:maximize-16-regular"

[minimize]
iconify = "fluent:subtract-24-regular"

[new-task]
file = "new-task.svg"

[open]
iconify = "fluent:open-20-regular"

[people]
iconify = "fluent-color:people-24"

[play]
iconify = "fluent:play-24-regular"

[plus]
iconify = "fluent:add-32-light"

[proc-filled]
file = "proc-filled.svg"

[proc-regular]
file = "proc-regular.svg"

[prohibited]
iconify = "fluent:prohibited-24-regular"

[pulse-filled]
file = "pulse-filled.svg"

[pulse-regular]
file = "pulse-regular.svg"

[puzzle]
iconify = "fluent-color:puzzle-piece-24"

[refresh]
iconify = "fluent:arrow-sync-24-regular"

[restore]
file = "restore.svg"

[search]
iconify = "fluent:search-24-regular"

[settings]
iconify = "fluent-color:settings-24"

[settings-filled]
iconify = "fluent:settings-24-filled"

[settings-regular]
iconify = "fluent:settings-24-regular"

[spinner]
iconify = "fluent:spinner-ios-20-regular"

[statistics]
iconify = "fluent-color:data-trending-24"

[stop]
iconify = "fluent:stop-24-regular"

[terminate]
iconify = "fluent:dismiss-circle-24-regular"

[uniproc-logo]
file = "uniproc-logo.svg"

[sys.application.icon]
file = "app.svg"
windows-ico = "icon.ico"
