[ui.services]
viewport = false
column_resized = false

[ui.processes]
viewport = false
column_resized = false

[ui.navigation]
sidebar_width = false

[ui.window]
config_changed = false


[context.settings]
watch = false
diff = false

[core.bus]
publish = false
deliver = false
subscribe = true

[core.actor]
bg = false
result = false


[policy]
disable_messages = [
    "model::ScanTick",
    "actor::Ping",
    "traits::NoOp",
    "agents::WindowsReportMessage",
    "process_snapshot_actor::ProcessSnapshotReady",
    "snapshot_actor::ServiceSnapshotResult",
    "model::ServiceSnapshot",
]
disable_targets = [
    "UiProcessesAdapter::set_column_widths",
    "UiProcessesAdapter::set_column_metadata",
    "UiProcessesAdapter::set_total_processes_count",
    "UiServicesAdapter::set_total_services_count",
    "UiServicesAdapter::set_column_widths",
]
