[package]
name = "ui"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
windows = { workspace = true }
windows-canvas = { workspace = true }
windows-reactor = { workspace = true }
app-contracts = { workspace = true }
context = { workspace = true }
guinea = { workspace = true }
guinea-widgets = { workspace = true }
guinea-plugin-l10n = { workspace = true }
guicons = { workspace = true, features = ["windows-reactor"] }
amethystate = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
