import { Icon } from "icons.slint";
import { Theme } from "theme.slint";
component ControlBtn inherits Rectangle {
    in property <string> icon-key;
    in property <bool> is-close: false;
    in property <length> image-size: 16px;
    callback clicked();

    width: Theme.title_control_width;
    height: Theme.title_bar_height;
    background: touch.pressed ? (is-close ? Theme.title_close : Theme.title_control_pressed) : touch.has-hover ? (is-close ? Theme.title_close : Theme.title_control_hover) : transparent;

    touch := TouchArea {
        clicked => {
            root.clicked()
        }
    }

    Icon {
        name: root.icon-key;
        width: root.image-size;
        height: root.image-size;
        colorize: (is-close && touch.has-hover) ? Theme.title_icon_active : Theme.title_icon;
    }
}

export component WindowControls inherits HorizontalLayout {
    spacing: 0px;
    alignment: end;
    in property <bool> minimizable: true;
    in property <bool> maximizable: true;
    in property <bool> is-maximized: false;

    callback minimize();
    callback maximize();
    callback close();

    if (minimizable): ControlBtn {
        icon-key: "minimize";
        clicked => {
            root.minimize()
        }
    }

    if (maximizable): ControlBtn {
        icon-key: root.is-maximized ? "restore" : "maximize";
        image-size: 14px;
        clicked => {
            root.maximize()
        }
    }

    ControlBtn {
        icon-key: "dismiss";
        is-close: true;
        clicked => {
            root.close()
        }
    }
}
