
import { ProcessesFeatureGlobal } from "../features/processes/globals.slint";
import { TabBar } from "../features/tabs/index.slint";
import { WindowControls } from "controls.slint";
import { Theme } from "theme.slint";
import { UniprocLogoIcon } from "icons.slint";

export global WindowClickHandler {
    callback window-clicked();

    window-clicked => {
        ProcessesFeatureGlobal.select_process(-1, -1);
    }
}

export global TitleBarActions {
    callback drag();
    callback close();
    callback minimize();
    callback maximize();
}

export component TitleBar {

    height: Theme.title_bar_height;
    unfocus := TouchArea {
        pointer-event(evt) => {
            if (evt.kind == PointerEventKind.down) {
                WindowClickHandler.window-clicked();
            }
        }
    }

    Rectangle {
        HorizontalLayout {
            spacing: 10px;
            padding-left: Theme.spacingHorizontalL;
            VerticalLayout {
                alignment: center;
                UniprocLogoIcon {
                    width: 24px;
                    height: 16px;
                    image-fit: contain;
                }

                TouchArea {
                    moved => {
                        TitleBarActions.drag();
                    }
                }
            }

            TabBar { }

            Rectangle {
                //???
                horizontal-stretch: 999;
                height: parent.height;

                TouchArea {
                    moved => {
                        TitleBarActions.drag();
                    }
                }
            }

            WindowControls {
                minimize => {
                    TitleBarActions.minimize();
                }
                maximize => {
                    TitleBarActions.maximize();
                }
                close => {
                    TitleBarActions.close();
                }
            }
        }
    }
}
