#[derive(guinea::Mark, Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProcessesSettingsMark {
    Back,
    Shown,
    Up,
    Down,
    ResetSections,
}

#[derive(guinea::Mark, Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProcessesMark {
    EndTask,
    OpenSettings,
    GroupByType,
    Chevron,
    Exited,
    NotRunning,
    PinnedRule,
    SectionGrip,
    DropLine,
    WslNotes,
    StatusReserve,
    StatusShare,
    Menu,
    MenuPin,
    MenuUnpin,
    MenuBackdrop,
    MenuEndTask,
    MenuSuspend,
    MenuResume,
    MenuOpenFileLocation,
    MenuProperties,
    MenuSearchOnline,
    MenuSwitchTo,
    MenuMinimize,
    MenuMaximize,
    MenuCloseWindow,
    MenuColumnPid,
    MenuColumnProcessName,
    MenuColumnCpu,
    MenuColumnMemory,
    MenuColumnNet,
    MenuColumnDisk,
}
