#[derive(guinea::Mark, Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProcessesMark {
    EndTask,
    GroupByType,
    Chevron,
    Exited,
    NotRunning,
    PinnedRule,
    WslNotes,
    StatusReserve,
    StatusShare,
    Menu,
    MenuPin,
    MenuUnpin,
    MenuBackdrop,
    MenuEndTask,
    MenuSuspend,
    MenuResume,
    MenuOpenFileLocation,
    MenuProperties,
    MenuSearchOnline,
    MenuSwitchTo,
    MenuMinimize,
    MenuMaximize,
    MenuCloseWindow,
}
