[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
windows = { workspace = true, features = ["libloaderapi"] }
windows-bindgen = { git = "https://github.com/microsoft/windows-rs", rev = "c14074c45" }
serde_json = { workspace = true }
