import { ScrollView } from "std-widgets.slint";
import { Theme } from "theme.slint";
import { EnvsLoading, EnvironmentsFeatureGlobal } from "../globals.slint";
import { Icon, ArrowUpRegularIcon, LayerFilledIcon } from "icons.slint";
import { L10n } from "localization.slint";

component DropdownItem inherits Rectangle {
    in property <string> text;
    in property <image> icon;
    in property <string> icon-key;
    in property <int> latency-ms: -1;
    in property <bool> show-latency: false;
    in property <bool> is-running;
    height: 36px;
    border-radius: 6px;
    animate background { duration: Theme.primary_animation_time; }

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        spacing: 10px;

        VerticalLayout {
            alignment: center;
            if (text == EnvironmentsFeatureGlobal.host-name && root.icon-key != ""): Icon {
                name: root.icon-key;
                width: 16px;
                height: 16px;
            }
            if (text == EnvironmentsFeatureGlobal.host-name && root.icon-key == ""): Image {
                source: root.icon;
                width: 16px;
                height: 16px;
                image-fit: contain;
            }
            if (text != EnvironmentsFeatureGlobal.host-name && root.icon-key != ""): Icon {
                name: root.icon-key;
                width: 16px;
                height: 16px;
                colorize: is-running ? Theme.accent_2 : Theme.text_secondary;
            }
            if (text != EnvironmentsFeatureGlobal.host-name && root.icon-key == ""): Image {
                source: root.icon;
                width: 16px;
                height: 16px;
                colorize: is-running ? Theme.accent_2 : Theme.text_secondary;
                image-fit: contain;
            }
        }

        Text {
            text: root.text;
            color: Theme.text_secondary;
            vertical-alignment: center;
            font-size: Theme.font_size_body;
            animate color { duration: Theme.primary_animation_time; }
        }

        Rectangle { }

        if (root.show-latency): Rectangle {
            width: 8px;
            height: 8px;
            border-radius: Theme.border_radius_s;
            y: (parent.height - self.height) / 2;
            background: latency-ms == -1 ? Theme.warn : Theme.success;
        }
    }
}

export component Environments inherits Rectangle {
    height: 40px;
    border-radius: 6px;
    in property <bool> is-collapsed;
    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            dropdown.show();
        }
    }

    HorizontalLayout {
        padding-left: 11px;
        padding-right: 12px;
        spacing: 12px;

        VerticalLayout {
            alignment: center;
            LayerFilledIcon {
                width: 20px;
                height: 20px;
            }
        }

        VerticalLayout {
            alignment: center;

            Text {
                text: L10n.environments;
                visible: !root.is-collapsed;
                color: Theme.text_primary;
                font-weight: 600;
                font-size: Theme.font_size_body;
                vertical-alignment: center;
            }
        }

        Rectangle { }

        VerticalLayout {
            alignment: center;

            ArrowUpRegularIcon {
                image-fit: contain;
                width: 12px;
                height: 12px;
                colorize: rgba(255, 255, 255, 0.5);
                transform-origin: { x: 4.5px, y: 6px };
                transform-rotation: 270deg;
                animate transform-rotation {
                    duration: Theme.primary_animation_time * 1.25;
                    easing: ease-out;
                }
            }
        }

        if (EnvsLoading.wsl-is-loading || EnvsLoading.wsl-distros-is-loading): Rectangle {
            width: 8px;
            height: 8px;
            border-radius: 4px;
            background: Theme.warn;
        }
    }

    dropdown := PopupWindow {
        width: root.width;
        Rectangle {
            border-radius: 8px;
            background: Theme.background;
            border-width: 1px;
            border-color: Theme.fill_subtle_secondary;

            menu-layout := VerticalLayout {
                padding: 4px;
                spacing: 2px;

                DropdownItem {
                    text: EnvironmentsFeatureGlobal.host-name;
                    icon: EnvironmentsFeatureGlobal.host-icon;
                    icon-key: EnvironmentsFeatureGlobal.host-icon-key;
                }

                if (EnvironmentsFeatureGlobal.has-wsl): ScrollView {
                    height: min(180px, EnvironmentsFeatureGlobal.wsl-distros.length * 36px + 2px);
                    vertical-scrollbar-policy: ScrollBarPolicy.as-needed;

                    VerticalLayout {
                        spacing: 2px;
                        for distro in EnvironmentsFeatureGlobal.wsl-distros: DropdownItem {
                            text: distro.name;
                            icon: distro.icon;
                            icon-key: distro.icon-key;
                            latency-ms: distro.latency-ms;
                            is-running: distro.is_running;
                            show-latency: true;
                        }
                    }
                }
            }
        }
    }
}
