import { Theme } from "theme.slint";
import { TableColWidth, TableColDef, TableCellData, TableColMetadata } from "types.slint";
import { GenericMasterCell } from "row-master-cell.slint";
import { GenericTableCell } from "row-cell.slint";
import { ContextMenu, ContextMenuItem } from "context-menu.slint";
export component GenericTableRow inherits Rectangle {
    in property <bool> selected;
    in property <bool> is-alternate;

    in property <[TableColDef]> column-defs;
    in property <[TableColWidth]> column-widths;
    in property <[TableColMetadata]> column-metadatas;


    in property <string> master-text;
    in property <image> master-icon;
    in property <string> master-icon-key;
    in property <color> master-icon-color;
    in property <bool> has-master-icon-color;
    in property <int> depth: 0;
    in property <bool> has-children: false;
    in property <bool> is-expanded: false;
    in property <bool> is-expandable: false;
    in property <color> master-color: white;

    in property <[TableCellData]> cells;

    in property <[ContextMenuItem]> context-menu-items;
    callback context-menu-action(string);
    callback right-clicked(length, length);

    callback clicked();
    callback toggle-expand();

    height: 32px;
    background: root.selected ? Theme.accent_2.with-alpha(0.1) :
                (touch.has-hover ? rgba(255,255,255,0.05) :
                (root.is-alternate ? Theme.fill_row_subtle : transparent));

    property <bool> menu-entering: false;

    menu-enter-timer := Timer {
        interval: 1ms;
        running: false;
        triggered => {
            menu-enter-timer.running = false;
            root.menu-entering = true;
        }
    }

    popup := ContextMenu {
        items: root.context-menu-items;
        x: touch.mouse-x;
        y: touch.mouse-y;
        is-entering: root.menu-entering;

        changed visible => {
            if (!self.visible) {
                root.menu-entering = false;
            }
        }


        action(id) => {
            root.context-menu-action(id);
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.up) {
                if (event.button == PointerEventButton.left) {
                    root.clicked();
                } else if (event.button == PointerEventButton.right) {
                    root.right-clicked(root.absolute-position.x + self.mouse-x, root.absolute-position.y + self.mouse-y);

                    if (root.context-menu-items.length > 0) {
                        root.menu-entering = false;
                        menu-enter-timer.running = true;
                        popup.show();
                    }
                }
            }
        }
    }

    HorizontalLayout {
        for col-def[idx] in root.column-defs : Rectangle {
            width: root.column-widths[idx].width-px * 1px;
            clip: true;

            if (idx == 0) : GenericMasterCell {
                text: root.master-text;
                icon: root.master-icon;
                icon-key: root.master-icon-key;
                has-icon-color: root.has-master-icon-color;
                icon-color: root.master-icon-color;
                depth: root.depth;
                has-children: root.has-children;
                is-expanded: root.is-expanded;
                is-expandable: root.is-expandable;
                text-color: root.master-color;
                toggle-expand => { root.toggle-expand(); }
            }

            if (idx > 0) : GenericTableCell {
                data: root.cells[idx - 1];
                is-simple-text: root.column-metadatas[idx].is-text;
            }
        }
    }
}
