use forsl_codegen::stub_gen;
use forsl_core::contracts::{BindingStubMeta, PortStubMeta};
use quote::{format_ident, quote};
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

const CONTRACTS_CRATE: &str = "app_contracts";

#[derive(Default)]
struct FeatureTraits {
    ports: Vec<&'static PortStubMeta>,
    bindings: Vec<&'static BindingStubMeta>,
}

fn main() {
    force_link_app_contracts();

    let mut features_map: BTreeMap<&'static str, FeatureTraits> = BTreeMap::new();

    for port in forsl_core::contracts::ports() {
        features_map.entry(port.feature).or_default().ports.push(port);
    }
    for binding in forsl_core::contracts::bindings() {
        features_map
            .entry(binding.feature)
            .or_default()
            .bindings
            .push(binding);
    }

    let mut final_code = quote! {
        // AUTO-GENERATED by domain-test-kit/build.rs
        use std::cell::RefCell;
        use std::rc::Rc;
        use slint::SharedString;
        use context::page_status::*;
    };

    for feature in features_map.keys() {
        let feature_ident = format_ident!("{}", feature);
        final_code.extend(quote! {
            use app_contracts::features::#feature_ident::*;
        });
    }

    for (feature, traits) in features_map {
        final_code.extend(stub_gen::generate_feature_stub(
            feature,
            &traits.ports,
            &traits.bindings,
            CONTRACTS_CRATE,
            &resolve_type_override,
        ));
    }

    let formatted_code = stub_gen::format_code(final_code.to_string());

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("generated_stubs.rs"), formatted_code).unwrap();
}

/// `app-contracts` is a build-dependency purely for its `inventory::submit!`-
/// registered `forsl_core::contracts` entries; see the identical comment on
/// `slint-adapter/build.rs`'s copy of this function for the full explanation.
fn force_link_app_contracts() {
    let _ = std::hint::black_box(app_contracts::__force_link_anchor as fn());
}

/// Type names the registry's string-based `arg_types`/`msg_type_name`
/// entries don't resolve to via the default
/// `app_contracts::features::<feature>::<Ident>` convention (see
/// `forsl_codegen::stub_gen::generate_feature_stub`'s doc comment) -
/// `TabContextKey` lives under the `tabs` feature regardless of which
/// feature references it, and `PageId`/`TabId`/`PageStatus` live in
/// `context::page_status`, not `app-contracts` at all.
fn resolve_type_override(ident: &str) -> Option<syn::Path> {
    if ident == "TabContextKey" {
        return Some(syn::parse_str("app_contracts::features::tabs::TabContextKey").unwrap());
    }
    if matches!(ident, "PageId" | "TabId" | "PageStatus") {
        return Some(syn::parse_str(&format!("context::page_status::{ident}")).unwrap());
    }
    None
}
