import {
    TableColDef,
    TableColWidth,
    TableColMetadata,
    TableCellData,
} from "../../components/table/index.slint";

export struct ServiceEntry {
    name: string,
    display-name: string,
    pid: int,
    status: string,
    group: string,
    description: string,
    cells: [TableCellData],
}

export global ServicesFeatureGlobal {

    in property <[TableColDef]> column-defs:[
        { id: "name", label: "Name" },
        { id: "pid", label: "PID" },
        { id: "status", label: "Status" },
        { id: "group", label: "Group" },
        { id: "description", label: "Description" },
    ];

    in property <[TableColMetadata]> column-metadatas:[
        { is-text: true },
        { is-text: true },
        { is-text: true },
        { is-text: true },
        { is-text: true }
    ];

    in property <[TableColWidth]> column-widths:[
        { id: "name", width-px: 150 },
        { id: "pid", width-px: 80 },
        { id: "status", width-px: 100 },
        { id: "group", width-px: 120 },
        { id: "description", width-px: 100 },
    ];

    in property <[ServiceEntry]> service-rows:[];
    in property <ServiceEntry> selected-entry: {
        name: "AudioEndpointBuilder",
        display-name: "Windows Audio Endpoint Builder",
        pid: -1,
        status: "Running",
        group: "AudioGroup",
        description: "Manages audio devices for the Windows audio service.",
        cells: [],
    };

    in property <string> current-sort;
    in property <bool> current-sort-descending;
    in property <int> total-services-count;
    in property <bool> is-loading;

    in property <bool> start-button-active: false;
    in property <bool> stop-button-active: true;
    in property <bool> restart-button-active: true;
    in property <bool> properties-inline-open: false;

    callback open-system-services();
}
