import {
    TableColDef,
    TableColWidth,
    TableColMetadata,
    TableCellData,
} from "table/index.slint";

export struct ProcessEntry {
    pid: int,
    name: string,
    icon: image,
    depth: int,
    has-children: bool,
    is-expanded: bool,
    is-dead: bool,
    cells: [TableCellData],
}

export struct ProcessGroup {
    parent: ProcessEntry,
    children: [ProcessEntry],
}

export global ProcessesFeatureGlobal {
    in property <[TableColDef]> column-defs: [
        {
            id: "name",
            label: "Name",
            is-text: true,
        },
        {
            id: "cpu",
            label: "CPU",
            stat-text: "46%",
            stat-numeric: 46.0,
            threshold: 50.0,
            stat-detail: "1,4 GHz",
            show-indicator: true
        },
        {
            id: "memory",
            label: "Memory",
            stat-text: "71%",
            stat-numeric: 71.0,
            threshold: 80.0,
            stat-detail: "32,5/64GB",
            show-indicator: true
        },
        {
            id: "disk",
            label: "Disk",
            stat-text: "125 b/s",
            stat-numeric: 0.0,
            threshold: 70.0,
            show-indicator: false
        },
        {
            id: "net",
            label: "Network",
            stat-text: "55 kb/s",
            stat-numeric: 5.0,
            threshold: 70.0,
            show-indicator: false
        },
    ];
    in-out property <[TableColMetadata]> column-metadatas: [
        { is-text: true },
        { is-metric: true },
        { is-metric: true },
        { is-metric: true },
        { is-metric: true }
    ];
    in-out property <[TableColWidth]> column-widths: [
        { id: "name", width-px: 190 },
        { id: "cpu", width-px: 85 },
        { id: "memory", width-px: 120 },
        { id: "disk", width-px: 70 },
        { id: "net", width-px: 70 },
    ];

    in property <[ProcessGroup]> process-groups: [];
    in property <[ProcessEntry]> process-rows: [
        {
            pid: 1,
            name: "Taskmgr sucks",
            is-dead: false,
            is-expanded: true,
            depth: 0,
            has-children: true,
            cells: [
                { text: "12.5%", value: 12.5, threshold: 50.0 },
                { text: "1.4 GiB", value: 1.4, threshold: 1.0 },
                { text: "500 KiB/s", value: 75.0, threshold: 70.0 },
                { text: "100 KB/s", value: 100.0, threshold: 70.0 },
            ]
        }
    ];
    in-out property <int> selected-pid: -1;
    in property <string> selected-name;
    in property <string> current-sort;
    in property <bool> current-sort-descending;
    in property <bool> is-grouped;
    in property <int> total-processes-count;
    in property <bool> empty-state-visible: false;
    in property <string> empty-state-title: "";
    in property <string> empty-state-message: "";
}
