[package]
name = "app-contracts"
version.workspace = true
edition.workspace = true

[dependencies]
guinea = { workspace = true }
guinea-plugin-l10n = { workspace = true }
fluent-templates = { workspace = true }
fluent-bundle = { workspace = true }
unic-langid = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
guicons = { workspace = true }
serde = { workspace = true, features = ["rc"] }

[build-dependencies]
guinea-plugin-l10n-build = { workspace = true }
guicons-build = { workspace = true }

[lints]
workspace = true
