#[derive(guinea::Mark, Clone, Copy, PartialEq, Eq, Debug)]
pub enum ActivityMark {
    Came,
    Went,
    NewOnly,
    Series,
    Only,
    HideExe,
    HideFolder,
    HideLauncher,
    Picked,
    Search,
    ClearArea,
    Scatter,
    Card,
    Rows,
    Row,
    Selected,
    Menu,
    RowMenu,
    RowMenuBackdrop,
    LegendGroup,
    LegendOther,
    Stripe,
    PutIn,
    NewGroup,
    Facts,
    Empty,
    ManageGroups,
}

#[derive(guinea::Mark, Clone, Copy, PartialEq, Eq, Debug)]
pub enum ActivityGroupsMark {
    Back,
    Group,
    Rows,
    BuiltIn,
    Shown,
    Name,
    Colour,
    Up,
    Down,
    Delete,
    Rule,
    Hidden,
    ShowAgain,
    NothingHidden,
}
