[package]
name = "domain"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
app-contracts = { workspace = true }
guinea = { workspace = true }
guinea-widgets = { workspace = true }
amethystate = { workspace = true }
amethystate-guinea = { workspace = true }
guinea-plugin-store = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ogurpchik = { workspace = true }
uniproc-protocol = { workspace = true }
capnp = { workspace = true }
capnp-rpc = { workspace = true }
compio = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
windows = { workspace = true }
uniproc-windows-agent = { workspace = true }

[lints]
workspace = true
