import {
    Button,
    VerticalBox,
    HorizontalBox,
    StandardTableView,
    ComboBox,
} from "std-widgets.slint";
import { TitleBar } from "title/title-bar.slint";
import { ContentContainer } from "content/index.slint";
import { ServicesPageOverlay } from "pages/dashboard/subpages/services/index.slint";
import { SideBar } from "features/sidebar/index.slint";
import { ResizeHandler } from "components/resize-area.slint";
import { WslDistro } from "features/environments/globals.slint";
import { ServicesFeatureGlobal } from "features/services/globals.slint";
import { WindowSize, WindowAdapter } from "window-adapter.slint";
import { TabBar } from "features/tabs/index.slint";
export * from "globals-export.slint";

export component AppWindow inherits Window {

    min-width: 500px;
    min-height: 400px;

    no-frame: true;
    background: transparent;
    default-font-family: "Segoe UI Variable Display";
    always-on-top: false;
    
    callback start_resize(int);


    //TODO: remove to rust
    changed width => {
        WindowAdapter.window-width = root.width;
        if (root.width < 600px) {
            if (WindowAdapter.size != WindowSize.sm) {
                WindowAdapter.size = WindowSize.sm;
                WindowAdapter.size-changed(WindowSize.sm);
            }
        } else if (root.width < 1024px) {
            if (WindowAdapter.size != WindowSize.md) {
                WindowAdapter.size = WindowSize.md;
                WindowAdapter.size-changed(WindowSize.md);
            }
        } else {
            if (WindowAdapter.size != WindowSize.lg) {
                WindowAdapter.size = WindowSize.lg;
                WindowAdapter.size-changed(WindowSize.lg);
            }
        }
    }

    VerticalLayout {
        padding: 0;
        spacing: 0;

        TitleBar { }
        
        HorizontalLayout {
            ContentContainer {
            }
        }
    }

    ServicesPageOverlay {
        visible: ServicesFeatureGlobal.properties-inline-open;
        width: root.width;
        height: root.height;
        z: 2000;
    }

    ResizeHandler {
        resize_requested(dir) => {
            root.start_resize(dir);
        }
    }
}
