export global EnvsLoading {
    in property <bool> wsl-distros-is-loading: true;
    in property <bool> wsl-is-loading: true;
}

export struct WslDistro {
    name: string,
    is_installed: bool,
    is_running: bool,
    icon: image,
    icon-key: string,
    latency_ms: int,
}

export global EnvironmentsFeatureGlobal {
    in property <bool> has-wsl: true;
    in property <[WslDistro]> wsl-distros: [];
    in property <string> host-name: "Windows";
    in property <image> host-icon;
    in property <string> host-icon-key: "";

    in-out property <string> selected-env: host-name;

    callback install-agent(string);
}
