[package]
name = "desktop"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
app-contracts = { workspace = true }
domain = { workspace = true }
guinea = { workspace = true }
ui = { workspace = true }
guicons = { workspace = true, features = ["windows-reactor"] }
amethystate = { workspace = true }
guinea-plugin-store = { workspace = true }
guinea-plugin-l10n = { workspace = true }
guinea-plugin-devtools = { workspace = true }
guinea-plugin-single-instance = { workspace = true }
guinea-widgets = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
unic-langid = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
windows-collections = { workspace = true }
windows-core = { workspace = true }
windows-reference = { workspace = true }
windows-reactor = { workspace = true }
dhat = { version = "0.3", optional = true }

[features]
dhat-heap = ["dep:dhat"]

[dev-dependencies]
guinea = { workspace = true, features = ["harness"] }
guinea-plugin-store = { workspace = true, features = ["test-utils"] }
futures = { workspace = true }
tempfile = "3"

[build-dependencies]
windows-reactor-setup = { workspace = true }
guinea-meta-build = { workspace = true }

[lints]
workspace = true
